"""
Narrative line-reuse instrumentation for Hero Adventure.

Drives the interactive GameController (not the fast-sim engine API) through
full headless playthroughs, since narration text is only ever generated by
the controller. Collects controller.line_usage_counts per run and reports
which (category:index) template lines got reused more than the target of
3 times within a single playthrough - see dumb.md/smart.md item #14/#15.
"""

import argparse
import random
from collections import Counter

from game_data import CLASSES, HOUSES
from game_controller import GameController

MAX_STEPS = 600
REUSE_TARGET = 3


def _pick_levelup_weights(hero_class):
    all_skills = ["fighting", "defending", "magic", "stealth", "salvaging", "speech"]
    if hero_class == "Hitter":
        weights = [3, 3, 1, 1, 2, 1]
    elif hero_class == "Blaster":
        weights = [1, 3, 3, 3, 1, 1]
    else:
        weights = [1, 1, 3, 3, 3, 1]
    return all_skills, weights


def run_single_playthrough(hero_class=None, run_id=0):
    """Auto-plays one full game via GameController.dispatch(). Returns
    (line_usage_counts, won, steps_used)."""
    hero_class = hero_class or random.choice(list(CLASSES.keys()))
    controller = GameController()
    controller.dispatch("new_game")
    controller.set_pending_name(f"Hero_{run_id}")
    controller.dispatch(f"select_class:{hero_class}")

    steps = 0
    while steps < MAX_STEPS:
        steps += 1
        screen = controller.screen
        e = controller.engine

        if screen == "origin_story":
            controller.dispatch("origin_continue")
        elif screen == "journey":
            controller.dispatch("advance_event")
        elif screen == "dungeon_found":
            controller.dispatch("enter_dungeon" if e.hp > 50 else "ignore_dungeon")
        elif screen in ("dungeon_floor_preview", "dungeon_boss_preview"):
            if e.hp < 50:
                controller.dispatch("exit_dungeon")
            else:
                controller.dispatch("engage_floor")
        elif screen == "super_monster_preview":
            controller.dispatch("fight_super_monster" if e.hp >= 60 else "ignore_super_monster")
        elif screen == "combat":
            monster = controller.ctx.get("monster_name")
            choice = e.get_tactical_choice(monster)
            controller.dispatch(choice)
        elif screen == "combat_result":
            controller.dispatch("combat_continue")
        elif screen == "loot_screen":
            controller.dispatch("loot_continue")
        elif screen == "dungeon_victory":
            controller.dispatch("dungeon_victory_continue")
        elif screen == "wandering_trader":
            controller.dispatch("leave_trader")
        elif screen == "magic_shrine_event":
            controller.dispatch("magic_shrine_continue")
        elif screen == "town_recovery":
            if controller.ctx.get("town_job_offer"):
                controller.dispatch("town_leave")
            elif controller.ctx.get("town_fully_healed"):
                controller.dispatch("town_leave")
            else:
                controller.dispatch("town_work")
        elif screen == "level_up":
            skills, weights = _pick_levelup_weights(hero_class)
            for skill in random.choices(skills, weights=weights, k=3):
                controller.dispatch(f"pick_levelup_skill:{skill}")
            controller.dispatch("levelup_continue")
        elif screen == "capital":
            afforded = [h for h in HOUSES if e.cash >= h["cost"]]
            if afforded:
                best = max(afforded, key=lambda h: h["cost"])
                controller.dispatch(f"buy_house:{best['name']}")
            else:
                controller.dispatch("keep_pension")
        elif screen in ("capital_result", "death"):
            break
        else:
            break

    return controller.line_usage_counts, controller.screen == "capital_result", steps


def run_instrumentation(num_runs):
    overall_max = Counter()
    overrun_run_counts = Counter()
    total_overruns = 0

    for i in range(1, num_runs + 1):
        usage, _won, _steps = run_single_playthrough(run_id=i)
        for key, count in usage.items():
            if count > overall_max[key]:
                overall_max[key] = count
            if count > REUSE_TARGET:
                overrun_run_counts[key] += 1
                total_overruns += 1

    print(f"Ran {num_runs} headless playthroughs via GameController.")
    print(f"Distinct narration lines seen: {len(overall_max)}")
    print(f"Lines exceeding {REUSE_TARGET} reuses in at least one playthrough: {len(overrun_run_counts)}")
    print(f"Total (run, line) overrun incidents: {total_overruns}")

    if overrun_run_counts:
        print("\nTop offending lines (by number of playthroughs where reuse > target):")
        for key, run_count in overrun_run_counts.most_common(20):
            print(f"  {key:<40} max_in_a_run={overall_max[key]:<3} playthroughs_over_target={run_count}")
    else:
        print(f"\nNo line exceeded {REUSE_TARGET} reuses in any single playthrough.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Hero Adventure narration line-reuse instrumentation")
    parser.add_argument("--runs", type=int, default=50, help="Number of headless playthroughs (default: 50)")
    parser.add_argument("--seed", type=int, default=None, help="Optional random seed for reproducibility")
    args = parser.parse_args()
    if args.seed is not None:
        random.seed(args.seed)
    run_instrumentation(args.runs)
